default_language_version:
  python: python3
repos:
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
            "--exclude=__init__.py",
            "--remove-duplicate-keys",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        exclude: /README\.rst$|\.pot?$
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-merge-conflict
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        name: pylint with optional checks
        args: ["--rcfile=.pylintrc", "--exit-zero"]
        verbose: true
        additional_dependencies: ["pylint-odoo==5.0.4"]
      - id: pylint
        name: pylint with mandatory checks
        args: ["--rcfile=.pylintrc-mandatory"]
        additional_dependencies: ["pylint-odoo==5.0.4"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length=120", "--exclude=__init__.py"]
        exclude: ^(__init__.py)
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8 except __init__.py
        args: ["--max-line-length=120", "--exclude=__init__.py"]
        exclude: ^(__init__.py)
        additional_dependencies: ["flake8-bugbear==21.9.2"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: ["--keep-percent-format"]
        exclude: ^(__init__.py)
